// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeUvLcMKZedcKa0k6532sG2KfhT-6rbo',
    appId: '1:217262401816:web:8e28964583b3c41c79566d',
    messagingSenderId: '217262401816',
    projectId: 'myproperty-app',
    authDomain: 'myproperty-app.firebaseapp.com',
    storageBucket: 'myproperty-app.appspot.com',
    measurementId: 'G-V61F4YCGVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6_dSVey5hZMi_yiV4nyG2mFFYygiOS4',
    appId: '1:217262401816:android:79923639992628c679566d',
    messagingSenderId: '217262401816',
    projectId: 'myproperty-app',
    storageBucket: 'myproperty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ryjj9pKkf9iWSIe3nNn_2KVka6iSsx8',
    appId: '1:217262401816:ios:74e099147ae080f879566d',
    messagingSenderId: '217262401816',
    projectId: 'myproperty-app',
    storageBucket: 'myproperty-app.appspot.com',
    iosBundleId: 'com.example.wishlistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ryjj9pKkf9iWSIe3nNn_2KVka6iSsx8',
    appId: '1:217262401816:ios:74e099147ae080f879566d',
    messagingSenderId: '217262401816',
    projectId: 'myproperty-app',
    storageBucket: 'myproperty-app.appspot.com',
    iosBundleId: 'com.example.wishlistapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzeUvLcMKZedcKa0k6532sG2KfhT-6rbo',
    appId: '1:217262401816:web:fa9b8ce0b60880c879566d',
    messagingSenderId: '217262401816',
    projectId: 'myproperty-app',
    authDomain: 'myproperty-app.firebaseapp.com',
    storageBucket: 'myproperty-app.appspot.com',
    measurementId: 'G-1M2M18TG9B',
  );
}
